name: Linux Release
permissions:
  contents: write

on:
  push:
    tags:
      - '*'
  workflow_dispatch:
    inputs:
      name:
        description: 'reason'
        required: false
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '>=1.21.6'
      - name: Build Backend (amd64)
        run: |
          cmd="go build"
          args="-gcflags=-trimpath=$(pwd) -asmflags=-trimpath=$(pwd)"
          GOOS=linux GOARCH=amd64 ${cmd} ${args} -ldflags "-s -w -extldflags '-static'" -o linux-server server.go

      - name: Build Backend (arm64)
        run: |
          cmd="go build"
          args="-gcflags=-trimpath=$(pwd) -asmflags=-trimpath=$(pwd)"
          GOARM=7 GOOS=linux GOARCH=arm ${cmd} ${args} -ldflags "-s -w -extldflags '-static'" -o linux-server-arm64 server.go

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            linux-server
            linux-server-arm64
          draft: true
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
